services:
  py-mysql:
    build: .  # Construye la imagen de tu aplicación desde el Dockerfile en el directorio actual
    ports:
      - "5000:5000"  # Exposición del puerto 5000 para tu aplicación (API)
    depends_on:
      - mysql  # Se asegura de que MySQL esté disponible antes de iniciar la aplicación
    networks: 
      - api-network  # Define la red donde interactúan los contenedores
  mysql:
    image: mysql:5.7  # Usa la imagen de MySQL versión 5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: inventory
    ports:
      - "3306:3306"  # Exposición del puerto 3306 para MySQL
    networks: 
      - api-network  # Red compartida entre los servicios

networks: 
  api-network: 
    driver: bridge  # Define un controlador de red "bridge" para la comunicación entre contenedores
