openapi: 3.0.0
info:
  title: API de Clientes
  description: API para gestionar registros de clientes.
  version: 1.0.0
servers:
  - url: http://3.225.233.88:5000
    description: Servidor de desarrollo
paths:
  /clientes:
    get:
      summary: Obtener todos los clientes
      responses:
        '200':
          description: Un arreglo JSON de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_cliente:
                      type: integer
                    nombre:
                      type: string
                    apellido:
                      type: string
                    edad:
                      type: integer
                    numero:
                      type: string
                    correo:
                      type: string
    post:
      summary: Crear un nuevo cliente
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                apellido:
                  type: string
                edad:
                  type: integer
                numero:
                  type: string
                correo:
                  type: string
      responses:
        '201':
          description: Cliente creado correctamente
  /clientes/{id_cliente}:
    parameters:
      - in: path
        name: id_cliente
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un cliente por ID
      responses:
        '200':
          description: Un objeto de cliente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_cliente:
                    type: integer
                  nombre:
                    type: string
                  apellido:
                    type: string
                  edad:
                    type: integer
                  numero:
                    type: string
                  correo:
                    type: string
        '404':
          description: Cliente no encontrado
    put:
      summary: Actualizar un cliente por ID
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                apellido:
                  type: string
                edad:
                  type: integer
                numero:
                  type: string
                correo:
                  type: string
      responses:
        '200':
          description: Cliente actualizado correctamente
        '404':
          description: Cliente no encontrado
    delete:
      summary: Eliminar un cliente por ID
      responses:
        '200':
          description: Cliente eliminado correctamente
        '404':
          description: Cliente no encontrado
